CREATE TABLE IF NOT EXISTS repo_level_stats (
    period_start_date DATE NOT NULL,
    period_end_date DATE NOT NULL,
    name VARCHAR(255) NOT NULL,
    owner VARCHAR(255) NOT NULL,
    name_with_owner VARCHAR(512) NOT NULL,
    description TEXT,
    is_archived BOOLEAN,
    is_fork BOOLEAN,
    stargazers_count INTEGER,
    forks_count INTEGER,
    watchers_count INTEGER,
    issues_count INTEGER,
    primary_language VARCHAR(100),
    repository_topics TEXT,
    best_streak INTEGER DEFAULT 0,
    coding_sessions_count INTEGER DEFAULT 0,
    most_comments_actor VARCHAR(255),
    most_commenter_comments_count INTEGER DEFAULT 0,
    commiters_count INTEGER DEFAULT 0,
    commiters_organizations_count INTEGER DEFAULT 0,
    new_branches_count INTEGER DEFAULT 0,
    new_tags_count INTEGER DEFAULT 0,
    opened_issues_count INTEGER DEFAULT 0,
    closed_issues_count INTEGER DEFAULT 0,
    resolved_issue_rate DOUBLE PRECISION DEFAULT 0.0,
    oldest_unresolved_issue_title TEXT,
    most_commented_issue_title TEXT,
    most_commented_issue_comments_count INTEGER DEFAULT 0,
    period_forks_count INTEGER DEFAULT 0,
    docs_pages_updated_count INTEGER DEFAULT 0,
    docs_updated_flag INTEGER,
    new_members_count INTEGER DEFAULT 0,
    opened_pull_requests_count INTEGER DEFAULT 0,
    closed_pull_requests_count INTEGER DEFAULT 0,
    most_pull_request_actor VARCHAR(255),
    period_stargazers_count INTEGER DEFAULT 0,
    ggazer_score DOUBLE PRECISION DEFAULT 0.0,
    activity_label VARCHAR(50),
    ggazer_rank INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (name_with_owner, period_start_date, period_end_date)
);

COMMENT ON TABLE repo_level_stats IS 'Repository level statistics and ggazer scores calculated per period';
